# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps' # Prefix for PRs related to dependencies
    open-pull-requests-limit: 5 # Maximum number of open PRs at a time
    rebase-strategy: 'auto' # Automatically rebase PRs if needed
    versioning-strategy: 'increase' # Strategy for version updates: increase only major/minor/patch
